### ISSUE TITLE
Javascript Channels Implementation

### ISSUE THREAD

**Issue by filipenanclarez** [berat-cakir/easy_web_view2#1]
Hi, this plugin is amazing.

Can you implement some way to interact with page with JavaScrip? Maybe using Javascript Channels like flutter_webview oficial widget?

**Comment by berat-cakir** [comment]
This plugin is based on flutter webview. JavaScript should work on it.

**Comment by filipenanclarez** [comment]
> This plugin is based on flutter webview. JavaScript should work on it.

javascriptChannels and javascriptMode parameters not working. 

Can you show a code example with Javascript Channels working?

**Comment by berat-cakir** [comment]
_javascriptMode_ and _channels_ are already set within the plugin once the official WebView is created. Check out **[mobile.dart](https://github.com/berat-cakir/easy_web_view2/blob/master/lib/src/mobile.dart)**:

![image](https://user-images.githubusercontent.com/44953263/122060869-4183cf80-cdee-11eb-8974-5a79d929d81e.png)

So, you can execute JS simply add it to the **[htmlContent ](https://github.com/berat-cakir/easy_web_view2/blob/master/example/lib/ui/home/screen.dart)** from the example:
![image](https://user-images.githubusercontent.com/44953263/122064559-86f5cc00-cdf1-11eb-9d09-faf5ffe64db4.png)

Enable the HTMLcontent and an alert will pop-up:
![image](https://user-images.githubusercontent.com/44953263/122064940-d4723900-cdf1-11eb-806f-45e2c285a478.png)


You may also check out: [this post](https://stackoverflow.com/a/64403741/8457850)

**Comment by filipenanclarez** [comment]
> _javascriptMode_ and _channels_ are already set within the plugin once the official WebView is created. Check out **[mobile.dart](https://github.com/berat-cakir/easy_web_view2/blob/master/lib/src/mobile.dart)**:
> 
> ![image](https://user-images.githubusercontent.com/44953263/122060869-4183cf80-cdee-11eb-8974-5a79d929d81e.png)
> 
> So, you can execute JS simply add it to the **[htmlContent ](https://github.com/berat-cakir/easy_web_view2/blob/master/example/lib/ui/home/screen.dart)** from the example:
> ![image](https://user-images.githubusercontent.com/44953263/122064559-86f5cc00-cdf1-11eb-9d09-faf5ffe64db4.png)
> 
> Enable the HTMLcontent and an alert will pop-up:
> ![image](https://user-images.githubusercontent.com/44953263/122064940-d4723900-cdf1-11eb-806f-45e2c285a478.png)
> 
> You may also check out: [this post](https://stackoverflow.com/a/64403741/8457850)

Firstly, i very appreciate your attention.

But still need understand how can i use this. I need to 'get' this events and use to show messages with flutter widgets by myself. So, how can i override you CrossWindowsEvent to get javascript message and process them by myself? 

And what about evaluateJavascript? How can i use this, with your encapsulated controler?

Regards

**Comment by filipenanclarez** [comment]
> > _javascriptMode_ and _channels_ are already set within the plugin once the official WebView is created. Check out **[mobile.dart](https://github.com/berat-cakir/easy_web_view2/blob/master/lib/src/mobile.dart)**:
> > ![image](https://user-images.githubusercontent.com/44953263/122060869-4183cf80-cdee-11eb-8974-5a79d929d81e.png)
> > So, you can execute JS simply add it to the **[htmlContent ](https://github.com/berat-cakir/easy_web_view2/blob/master/example/lib/ui/home/screen.dart)** from the example:
> > ![image](https://user-images.githubusercontent.com/44953263/122064559-86f5cc00-cdf1-11eb-9d09-faf5ffe64db4.png)
> > Enable the HTMLcontent and an alert will pop-up:
> > ![image](https://user-images.githubusercontent.com/44953263/122064940-d4723900-cdf1-11eb-806f-45e2c285a478.png)
> > You may also check out: [this post](https://stackoverflow.com/a/64403741/8457850)
> 
> Firstly, i very appreciate your attention.
> 
> But still need understand how can i use this. I need to 'get' this events and use to show messages with flutter widgets by myself. So, how can i override you CrossWindowsEvent to get javascript message and process them by myself?
> 
> And what about evaluateJavascript? How can i use this, with your encapsulated controler?
> 
> Regards

I think got it 


![image](https://user-images.githubusercontent.com/27212546/122083670-720c3f00-cdd7-11eb-976b-d1bd4e098325.png)

Now, can you extract the webviewcontroller? Then we can use evaluateJavascript method.

Regards

**Comment by berat-cakir** [comment]
Exactly! I was about to say that you can access CrossWindowEvents as shown in the example:
![image](https://user-images.githubusercontent.com/44953263/122084159-dba14300-ce01-11eb-9261-5cbe11a6a291.png)

Btw this plugin does not belong to me. I just updated it so that it works with null safety. So, use this only as a temporary solution until the original author updates his code: [Check it out here](https://pub.dev/packages/easy_web_view)

Regarding the controller: please open a ticket so that Rody will add this feature. For now, all you can do is to edit the plugin itself to make the controller accessible.
